### PR TITLE
feat: sqlite

### PR DESCRIPTION
**Pull request by faddat**
This is built from:

* #148 

... so please merge #148 first.

This PR allows Comet to use sqlite as the db backend.

### CODE REVIEW

**Comment by faddat** [comment]
whoa!

**Comment by melekes** [comment]
Interesting to see SQLite here 👍

**Comment by faddat** [comment]
I thought so too!

Gotta credit @assafmo for the idea, he asked if we had support and I thought... hm, why not!

**Comment by assafmo** [comment]
Bump

**Comment by adizere** [comment]
We can ship this in the next release, most likely in May.

**Comment by assafmo** [comment]
.

**Comment by assafmo** [comment]
.

**Comment by assafmo** [comment]
Hate this stale bot

**Comment by assafmo** [comment]
.

**Comment by melekes** [comment]
I'm going to close this as this is stale. @faddat @assafmo please let us know if/when you have time to finish this work.

**Pull request closed without merging**
