### PR TITLE
remove dbs no one uses

### PR DESCRIPTION
**Pull request by faddat**
- add pebbledb
- use latest pebble
- added a ton of test rigor and fixed linting
- if always false we don't need the param
- really we don't need that
- remove databases no one uses

### CODE REVIEW

**Comment by faddat** [comment]
I am okay with codecov propblems.  We should rip it out anyhow.

**Comment by faddat** [comment]
Sorry closing this one too.

Informal system should not use the pebble code for any reason at any time.

**Comment by jmalicevic** [comment]
Hi @faddat , thank you for the benchmarks and insights. As @adizere  [stated](https://github.com/cometbft/cometbft-db/issues/90#issuecomment-1883234181), we don't want to abruptly remove support for all other databases as we have a very large userbase still using them. We have plans to converge to one DB backend in the future but this requires an extensive study on what users are using. I would therefore separate the concerns of adding Pebble and removing other backends and keep in the PR only the addition of Pebble.

**Comment by faddat** [comment]
ok, I will change this to draft in that case.

**Comment by faddat** [comment]
Just so you know, somebody has written a universal converter. I just don't know who. It may have been The team that starts on a p but isn't persistence but I always forget their name

**Comment by faddat** [comment]
personally I dont care about tenths of a percent of on codecov.  Please let me know if it matters.

**Comment by faddat** [comment]
I think that this PR remains a good idea.

**Comment by adizere** [comment]
The PR would be a lot better without this commit a574117f5f01279e2d480135ce13a3ea32d481a7. It's difficult to review right now. Can you revert that commit?

**Comment by faddat** [comment]
100%

**Comment by faddat** [comment]
closing in favor of #115

**Pull request closed without merging**
