### PR TITLE
Release v0.7.1

### PR DESCRIPTION
**Pull request by thanethomson**
:book: [CHANGELOG rendered](https://github.com/cometbft/cometbft-db/blob/release/v0.7.1/CHANGELOG.md#v071)

### CODE REVIEW

**Comment by thanethomson** [comment]
By cutting this as v0.7.1, we will effectively be automatically rolling this out to anyone building their software using this version, meaning that the RocksDB update will automatically propagate to users. Should we instead cut this as v0.8.0 and have users deliberately update instead?

cc @yihuang @alexanderbez @robert-zaremba

**Comment by robert-zaremba** [comment]
I think someone already tested the new library (grocksdb) doesn't break the data (it should not).
So doing a point release makes sense. But let's re-confirm the above.

**Comment by yihuang** [comment]
> I think someone already tested the new library (grocksdb) doesn't break the data (it should not). So doing a patch release makes sense. But let's re-confirm the above.

yeah, the only breaking thing is to user's build dependencies, I think should be alright, there's probably not so many user building rocksdb right now I guess.

**Comment by thanethomson** [comment]
I tested this on our side and it breaks the build of our E2E testing image, which to me signals that this should be released in a new breaking release of cometbft-db (i.e. v0.8.0). I'll close this PR and open a follow-up one to release the same changes instead as v0.8.0.

**Pull request closed without merging**
